name: Build smolBSD image

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'www/**'
  workflow_dispatch:
    inputs:
      img:
        description: "Image target"
        required: true
        default: "base"
      arch:
        description: "Architecture"
        required: true
        default: "amd64"
      service:
        description: "Service to build on top of image"
        required: false
        default: "build"
      mountro:
        description: "Build as read-only (y or empty)"
        required: false
        default: "y"
      curlsh:
        description: "URL to a script to execute as finalizer"
        required: false
        default:

jobs:
  build_img:
    runs-on: ubuntu-latest
    container:
      image: debian:latest
      options: --privileged
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up environment
        run: |
          apt update && apt install -y curl xz-utils make sudo git libarchive-tools rsync bmake e2fsprogs
          rm -rf /var/cache

      - name: Build image
        run: |
          for arch in amd64 evbarm-aarch64
          do
            bmake SERVICE=${{ inputs.service }} NOSVCIMGBUILD=yes CURLSH=${{ inputs.curlsh }} ARCH="$arch" MOUNTRO=${{ inputs.mountro || 'y' }} ${{ inputs.img || 'buildimg' }}
          done

      - name: Compress images
        run: |
          cd images
          for f in *.img; do
            echo "Compressing $f..."
            xz -T0 -9e "$f"
            sha256sum ${f}.xz > ${f}.xz.sha256
          done
          rm -f *.img

      - name: Publish images to "latest" release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: "Latest smolBSD images (compressed)"
          files: |
            images/*.img.xz
            images/*.xz.sha256
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

